In [2]:
import numpy as np

In [3]:
arr = np.array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])
print(arr)

[0 0 3 0 2 4 2 2 2 2]


In [4]:
unique_vals, inverse_indices = np.unique(arr, return_inverse=True)
print(unique_vals)
print(inverse_indices)

[0 2 3 4]
[0 0 2 0 1 3 1 1 1 1]


In [5]:
for i in range(len(arr)):
    print(f"Position {i}: value {arr[i]} -> unique index {inverse_indices[i]}")

Position 0: value 0 -> unique index 0
Position 1: value 0 -> unique index 0
Position 2: value 3 -> unique index 2
Position 3: value 0 -> unique index 0
Position 4: value 2 -> unique index 1
Position 5: value 4 -> unique index 3
Position 6: value 2 -> unique index 1
Position 7: value 2 -> unique index 1
Position 8: value 2 -> unique index 1
Position 9: value 2 -> unique index 1


In [6]:
def find_duplicates(arr):
    result = []
    seen = []
    for value in arr:
        if value in seen:
            result.append(True)
        else:
            result.append(False)
            seen.append(value)
    return np.array(result)

result = find_duplicates(arr)
print(result)

[False  True False  True False False  True  True  True  True]


In [7]:
def find_duplicates_numpy(arr):
    unique_vals, inverse_indices = np.unique(arr, return_inverse=True)
    seen = np.zeros(len(unique_vals), dtype=bool)
    result = np.zeros(len(arr), dtype=bool)
    
    for i in range(len(arr)):
        unique_index = inverse_indices[i]
        if seen[unique_index]:
            result[i] = True
        else:
            seen[unique_index] = True
            result[i] = False
    
    return result

result = find_duplicates_numpy(arr)
print(result)

[False  True False  True False False  True  True  True  True]


In [8]:
arr = np.array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])
unique_vals, inverse_indices = np.unique(arr, return_inverse=True)
seen = np.zeros(len(unique_vals), dtype=bool)
result = np.zeros(len(arr), dtype=bool)

for i in range(len(arr)):
    unique_index = inverse_indices[i]
    if seen[unique_index]:
        result[i] = True
        print(f"Position {i}: {arr[i]} -> True (duplicate)")
    else:
        seen[unique_index] = True
        result[i] = False
        print(f"Position {i}: {arr[i]} -> False (first)")

print(result)

Position 0: 0 -> False (first)
Position 1: 0 -> True (duplicate)
Position 2: 3 -> False (first)
Position 3: 0 -> True (duplicate)
Position 4: 2 -> False (first)
Position 5: 4 -> False (first)
Position 6: 2 -> True (duplicate)
Position 7: 2 -> True (duplicate)
Position 8: 2 -> True (duplicate)
Position 9: 2 -> True (duplicate)
[False  True False  True False False  True  True  True  True]


In [11]:
t = int(input())
for _ in range(t):
    ids = list(map(int, input().split()))
    ids_array = np.array(ids)
    
    unique_vals, inverse_indices = np.unique(ids_array, return_inverse=True)
    seen = np.zeros(len(unique_vals), dtype=bool)
    result = np.zeros(len(ids_array), dtype=bool)
    
    for i in range(len(ids_array)):
        unique_index = inverse_indices[i]
        if seen[unique_index]:
            result[i] = True
        else:
            seen[unique_index] = True
            result[i] = False
    
    print(result)

 1
 0 0 3 0 2 4 2 2 2 2


[False  True False  True False False  True  True  True  True]


In [12]:
arr = np.array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])
unique_vals, inverse_indices = np.unique(arr, return_inverse=True)
seen = np.zeros(len(unique_vals), dtype=bool)
result = np.zeros(len(arr), dtype=bool)

for i in range(len(arr)):
    unique_index = inverse_indices[i]
    if seen[unique_index]:
        result[i] = True
    else:
        seen[unique_index] = True
        result[i] = False

print(result)

[False  True False  True False False  True  True  True  True]


In [13]:
test_arrays = [[1, 2, 3], [1, 1, 1], [1, 2, 1, 2]]
for test in test_arrays:
    arr = np.array(test)
    result = find_duplicates_numpy(arr)
    print(f"{test} -> {result}")

[1, 2, 3] -> [False False False]
[1, 1, 1] -> [False  True  True]
[1, 2, 1, 2] -> [False False  True  True]
