In [0]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [0]:
steps=[("Standard_scaler",StandardScaler()),
("classifier",LogisticRegression())]

In [0]:
steps

[('Standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [0]:
pipe=Pipeline(steps)
pipe

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [0]:
from sklearn import set_config

In [0]:
set_config(display="diagram")

In [0]:
pipe

Pipeline(steps=[('Standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [0]:
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000)

In [0]:
x.shape

(1000, 20)

In [0]:
 from sklearn.model_selection import train_test_split
 x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.33, random_state=42)
 x_train

array([[-0.84567576,  0.81549042, -1.22763435, ...,  0.50949572,
         0.9931541 , -0.96712904],
       [ 0.27960642,  0.75880551,  0.03966473, ...,  0.50787272,
        -0.07232342, -1.9732459 ],
       [-0.49669243, -0.73894597, -1.0935309 , ..., -0.65803205,
         0.09409413, -0.08805551],
       ...,
       [ 0.01581283, -0.92011099, -0.79103359, ..., -0.41094137,
         0.3870009 , -0.16918969],
       [-0.0480206 ,  0.03349342,  0.8490943 , ...,  0.05619333,
         2.78435826, -1.42116156],
       [-0.39052408,  0.48193444, -0.58318032, ...,  0.65126447,
        -0.70967705, -0.57325371]])

In [0]:
pipe.fit(x_train,y_train)
Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])
y_pred=pipe.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,

In [0]:
 from sklearn.decomposition import PCA
 from sklearn.svm import SVC

In [0]:
steps=[("scaling",StandardScaler()),
      ("PCA",PCA(n_components=3)),
      ("SVC",SVC())]
pipe2=Pipeline(steps)
pipe2.fit(x_train,y_train)
Pipeline(steps=[('scaling', StandardScaler()), ('PCA', 
PCA(n_components=3)),
                ('SVC', SVC())])
pipe2.predict(x_test)

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,

In [0]:
from sklearn.impute import SimpleImputer
import numpy as np
numeric_processor=Pipeline(

steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy="mean")),("scaler",StandardScaler())])
numeric_processor
Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
 ("onehot",OneHotEncoder(handle_unknown="ignore"))])
categorical_processor=Pipeline(steps=[('imputation_consatnt',SimpleImputer(fill_value='missing',
strategy='constant')),('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [0]:
from sklearn.compose import ColumnTransformer
preprocessor=ColumnTransformer(
 [("categorical",categorical_processor,["gender","City"]),
 ("numerical",numeric_processor,["age","height"])]
)
preprocessor
ColumnTransformer(transformers=[('categorical',

Pipeline(steps=[('imputation_consatnt',

SimpleImputer(fill_value='missing',

strategy='constant')),('onehot',

OneHotEncoder(handle_unknown='ignore'))]),
 ['gender', 'City']),
 ('numerical',
 Pipeline(steps=[('imputation_mean',
 SimpleImputer()),
 ('scaler',
StandardScaler())]),
 ['age', 'height'])])

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [0]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())
pipe
Pipeline(steps=[('columntransformer',
 ColumnTransformer(transformers=[('categorical',

Pipeline(steps=[('imputation_consatnt',

SimpleImputer(fill_value='missing',

strategy='constant')),('onehot',OneHotEncoder(handle_unknown='ignore'))]),['gender', 'City']),
 ('numerical',Pipeline(steps=[('imputation_mean',SimpleImputer()),
                ('scaler',StandardScaler())]),['age','height'])])),
                ('logisticregression', LogisticRegression())])

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])